[package]
name = "rangetools"
version = "0.1.0"
edition = "2021"
authors = ["rory <rjsnively@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.14"